tiposincidencias:
    path:     /
    defaults: { _controller: "prosgaBundle:TiposIncidencias:index" }

tiposincidencias_show:
    path:     /{id}/show
    defaults: { _controller: "prosgaBundle:TiposIncidencias:show" }

tiposincidencias_new:
    path:     /new
    defaults: { _controller: "prosgaBundle:TiposIncidencias:new" }

tiposincidencias_create:
    path:     /create
    defaults: { _controller: "prosgaBundle:TiposIncidencias:create" }
    requirements: { _method: post }

tiposincidencias_edit:
    path:     /{id}/edit
    defaults: { _controller: "prosgaBundle:TiposIncidencias:edit" }

tiposincidencias_update:
    path:     /{id}/update
    defaults: { _controller: "prosgaBundle:TiposIncidencias:update" }
    requirements: { _method: post|put }

tiposincidencias_delete:
    path:     /{id}/delete
    defaults: { _controller: "prosgaBundle:TiposIncidencias:delete" }
    requirements: { _method: post|delete }

tiposincidencias_graph:
    path:     /{id}/graph
    defaults: { _controller: "prosgaBundle:TiposIncidencias:graph" }