INFT\prosgaBundle\Entity\Actividad:
    type: entity
    table: Actividad
    repositoryClass: ActividadRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fechaActividad:
            type: datetime
            column: FechaActividad
        observacion:
            type: string
            length: 1000
            column: Observacion
        nombre:
            type: string
            length: 255
            column: Nombre
        aspectoAmbiental:
            type: string
            length: 1000
            column: AspectoAmbiental
        accionPrevencion:
            type: string
            length: 1000
            column: AccionPrevencion
    manyToOne:
        personaResponsable:
            targetEntity: Persona
            inversedBy: actividades
            joinColumn:
                name: persona_id
                referencedColumnName: id
        sector:
            targetEntity: Sector
            joinColumn:
                name: sector_id
                referencedColumnName: id
        proceso:
            targetEntity: Proceso
            joinColumn:
                name: proceso_id
                referencedColumnName: id            
        norma:
            targetEntity: Norma
            joinColumn:
                name: norma_id
                referencedColumnName: id            
        matrizlegal:
            targetEntity: MatrizLegal
            joinColumn:
                name: matrizLegal_id
                referencedColumnName: id            
        control:
            targetEntity: Control
            joinColumn:
                name: control_id
                referencedColumnName: id    
        auditoria:
            targetEntity: Auditoria
            joinColumn: 
                name: auditoria_id
                referencedColumnName: id
        
    lifecycleCallbacks: {  }
