INFT\prosgaBundle\Entity\Auditoria:
    type: entity
    table: Auditoria
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 250
            column: Nombre
        fechaDeAuditoria:
            type: datetime
            column: FechaDeAuditoria
        costoAuditoria:
            type: decimal
            column: CostoAuditoria
        observacion:
            type: string
            length: '1000'
            column: Observacion
    oneToOne:
        personaResponsable:
            targetEntity: Persona
            joinColumn: 
                name: responsable_id
                referencedColumnName: id
        sector:
            targetEntity: Sector
            joinColumn:
                name: sector_id
                referencedColumnName: id
        estado:
            targetEntity: Estado
            joinColumn:
                name: estado_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
