INFT\prosgaBundle\Entity\Cargo:
    type: entity
    table: Cargo
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '200'
            column: Nombre
        descripcion:
            type: string
            length: 255
            column: Descripcion
        nivelEnOrganigrama:
            type: integer
            column: NivelEnOrganigrama
        observacion:
            type: string
            length: 255
            column: Observacion
    lifecycleCallbacks: {  }
