INFT\prosgaBundle\Entity\Control:
    type: entity
    table: Control
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '200'
            column: Nombre
        descripcion:
            type: string
            length: '1000'
            nullable: true
            column: Descripcion
        fecha:
            type: datetime
            column: Fecha
        observacion:
            type: string
            length: '1000'
            nullable: true
            column: Observacion
            
    manyToOne:
        frecuencia:
            targetEntity: Frecuencia
            joinColumn:
                name: frecuencia_id
                referencedColumnName: id
        personaResponsable:
            targetEntity: Persona
            joinColumn:
                name: persona_id
                referencedColumnName: id
        fichaDeProceso:
            targetEntity: FichaDeProceso
            joinColumn:
                name: fichaDeProceso_id
                referencedColumnName: id
    manyToMany:
        sectores:
            targetEntity: Sector
            joinTable:
                name: ControlPorSector
                joinColumns:
                    control_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    sector_id:
                        referencedColumnName: id
                
    lifecycleCallbacks: {  }
