INFT\prosgaBundle\Entity\Documento:
    type: entity
    table: Documento
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 250
            column: Nombre
        fechaCreacion:
            type: datetime
            column: FechaCreacion
        ubicacion:
            type: string
            length: 255
            column: Ubicacion
            
    manyToOne:
        auditoria:
            targetEntity: Auditoria
            joinColumn:
                name: auditoria_id
                referencedColumnName: id
        proceso:
            targetEntity: Proceso
            joinColumn:
                name: proceso_id
                referencedColumnName: id
        estado:
            targetEntity: Estado
            joinColumn:
                name: estado_id
                referencedColumnName: id
        persona:
            targetEntity: Persona
            joinColumn:
                name: persona_id
                referencedColumnName: id
                
    manyToMany:
        permisos:
            targetEntity: Permiso
            joinTable:
                name: PermisoPorDocumento
                joinColumns:
                    permiso_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    documento_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
