INFT\prosgaBundle\Entity\DocumentoHistorial:
    type: entity
    table: DocumentoHistorial
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fechaModificacion:
            type: datetime
            column: FechaModificacion
        observacion:
            type: string
            length: '1000'
            column: Observacion            
    manyToOne:
        documento:
            targetEntity: Documento
            joinColumn: 
                name: documento_id
                referencedColumnName: id
        persona:
            targetEntity: Persona
            joinColumn:
                name: persona_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
