INFT\prosgaBundle\Entity\Estado:
    type: entity
    table: Estado
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '200'
            column: Nombre
        observacion:
            type: string
            length: 255
            column: Observacion
    lifecycleCallbacks: {  }
