INFT\prosgaBundle\Entity\FichaDeProceso:
    type: entity
    table: FichaDeProceso
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        codigoDeFicha:
            type: string
            length: '100'
            column: CodigoDeFicha
        nombre:
            type: string
            length: 255
            column: Nombre
        fechaDeEmision:
            type: datetime
            column: FechaDeEmision
        fechaDeRevision:
            type: datetime
            column: FechaDeRevision
        nroDeRevision:
            type: integer
            column: NroDeRevision
        objetivo:
            type: string
            length: '1000'
            column: Objetivo
        alcance:
            type: string
            length: '500'
            column: Alcance
            
    manyToOne:
        personaPrepara:
            targetEntity: Persona
            joinColumn:
                name: persona_id
                referencedColumName: id
        personaAprueba:
            targetEntity: Persona
            joinColumn: 
                name: persona_id
                referencedColumName: id
        personaResponsable:
            targetEntity: Persona
            joinColumn:
                name: persona_id
                referencedColumName: id
                
    oneToOne:
        fichaDeProcesoAntecesor:
            targetEntity: FichaDeProceso
            joinColumn: 
                name: fichaDeProceso_id
                referencedColumName: id
        fichaDeProcesoPredecesor:
            targetEntity: FichaDeProceso
            joinColumn: 
                name: fichaDeProceso_id
                referencedColumName: id
        
    lifecycleCallbacks: {  }
