INFT\prosgaBundle\Entity\FichaDeProcesoHistorial:
    type: entity
    table: FichaDeProcesoHistorial
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fecha:
            type: datetime
            column: Fecha
        nroRevision:
            type: integer
            column: NroRevision
        descripcion:
            type: string
            length: '500'
            column: Descripcion
    manyToOne:
        fichaDeProceso:
            targetEntity: FichaDeProceso
            joinColumn:
                name: fichaDeProceso_id
                referencedColumnName: id
        persona:
            targetEntity: Persona
            joinColumn:
                name: persona_id
                referencedColumnName: id
    lifecycleCallbacks: {  }