INFT\prosgaBundle\Entity\Frecuencia:
    type: entity
    table: Frecuencia
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
            column: Nombre
        descripcion:
            type: string
            length: 255
            column: Descripcion
    
    oneToMany:
        alarmas:
            targetEntity: Alarma
            mappedBy: frecuencia
                
    lifecycleCallbacks: {  }
