INFT\prosgaBundle\Entity\Indicador:
    type: entity
    table: Indicador
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
            column: Nombre
        descripcion:
            type: string
            length: '500'
            column: Descripcion
        observacion:
            type: string
            length: '1000'
            column: Observacion
            
    manyToOne:
        frecuencia:
            targetEntity: Frecuencia
            joinColumn:
                name: frecuencia_id
                referencedColumnName: id
        fichaDeProceso:
            targetEntity: FichaDeProceso
            joinColumn:
                name: fichaDeProceso_id
                referencedColumnName: id
                
    lifecycleCallbacks: {  }
