INFT\prosgaBundle\Entity\Norma:
    type: entity
    table: Norma
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
            column: Nombre
        observacion:
            type: string
            length: '1000'
            nullable: true
            column: Observacion
            
    lifecycleCallbacks: {  }
