INFT\prosgaBundle\Entity\Persona:
    type: entity
    table: Persona
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
            column: Nombre
        apellido:
            type: string
            length: 255
            column: Apellido
        mail:
            type: string
            length: '200'
            column: Mail
        telefono:
            type: string
            length: '100'
            column: Telefono
        obligaciones:
            type: string
            length: '1000'
            column: Obligaciones
        observacion:
            type: string
            length: '1000'
            column: Observacion
            
    oneToOne:
        cargo:
            targetEntity: Cargo
            joinColumn:
                name: cargo_id
                referencedColumnName: id
        usuario:
            targetEntity: Usuario
            joinColumn:
                name: usuario_id
                referencedColumnName: id
        estado:
            targetEntity: Estado
            joinColumn:
                name: estado_id
                referencedColumnName: id 
                
    manyToMany:
        indicadores:
            targetEntity: Indicador
            joinTable: 
                name: ResponsablePorIndicador
                joinColumns:
                    indicador_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    persona_id:
                        referencedColumnName: id
        procedimientosGenerales:
            targetEntity: ProcedimientoGeneral
            joinTable:
                name: ResponsablePorProcedGeneral
                joinColumns:
                    persona_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    procedimientoGeneral_id:
                        referencedColumnName: id
        registrosFichaDeProceso:
            targetEntity: RegistroFP
            joinTable:
                name: ResponsablePorRegistroFP
                joinColumns:
                    persona_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    registroFP_id:
                        referencedColumnName: id
    oneToMany:
        actividades:
            targetEntity: Actividad
            mappedBy: personaResponsable
                    
    lifecycleCallbacks: {  }
