INFT\prosgaBundle\Entity\Proceso:
    type: entity
    table: Proceso
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
            column: Nombre
    manyToOne:
        norma:
            targetEntity: Norma
            joinColumn:
                name: norma_id
                referencedColumnName: id
        alarma:
            targetEntity: Alarma
            joinColumn: 
                name: alarma_id
                referencedColumnName: id
        estado:
            targetEntity: Estado
            joinColumn: 
                name: estado_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
