INFT\prosgaBundle\Entity\Proceso:
    type: entity
    table: Proceso
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
            column: Nombre
    ManyToOne:
        Norma:
            targetEntity: Norma
            joinColumn:
                name: IdNorma
                referencedColumnName: id
        Alarma:
            targetEntity: Alarma
            joinColumn: 
                name: IdAlarma
                referencedColumnName: id
        Estado:
            targetEntity: Estado
            joinColumn: 
                name: IdEstado
                referencedColumnName: id
    lifecycleCallbacks: {  }
