INFT\prosgaBundle\Entity\ProcedimientoGeneral:
    type: entity
    table: ProcedimientoGeneral
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        codigoProcedimiento:
            type: string
            length: '200'
            column: CodigoProcedimiento
        nombre:
            type: string
            length: 255
            column: Nombre
        fechaDeEmision:
            type: datetime
            column: FechaDeEmision
        fechaDeRevision:
            type: datetime
            column: FechaDeRevision
        nroRevision:
            type: integer
            column: NroRevision
        objetivos:
            type: string
            length: '1000'
            column: Objetivos
        alcance:
            type: string
            length: '2000'
            column: Alcance	  

    manyToOne:
        procedGeneralAntecesor:
            targetEntity: ProcedimientoGeneral
            joinColumn:
                name: procedimientoGeneral_id
                referencedColumnName: id
        procedGeneralPredecesor:
            targetEntity: ProcedimientoGeneral
            joinColumn:
                name: procedimientoGeneral_id
                referencedColumnName: id
                
    lifecycleCallbacks: {  }
