INFT\prosgaBundle\Entity\RegistroPG:
    type: entity
    table: RegistroPG
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        codigoPG:
            type: string
            length: '200'
            column: CodigoPG
        nombre:
            type: string
            length: '200'
            column: Nombre
        archivoFisico:
            type: string
            length: '500'
            nullable: true
            column: ArchivoFisico
        archivoDigital:
            type: string
            length: '500'
            nullable: true
            column: ArchivoDigital
        tiempoEnArchivo:
            type: datetime
            column: TiempoEnArchivo
        observacion:
            type: string
            length: '1000'
            nullable: true
            column: Observacion
            
    manyToOne:
        procedimientoGeneral:
            targetEntity: ProcedimientoGeneral
            joinColumn: 
                name: procedimientoGeneral_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
