INFT\prosgaBundle\Entity\RegistroFP:
    type: entity
    table: RegistroFP
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        codigoDeFicha:
            type: string
            length: 255
            column: CodigoDeFicha
        nombre:
            type: string
            length: 255
            column: Nombre
        ubicacionArchivoFisico:
            type: string
            length: 255
            nullable: true
            column: UbicacionArchivoFisico
        ubicacionArchivoDigital:
            type: string
            length: 255
            nullable: true
            column: UbicacionArchivoDigital
        tiempoEnArchivo:
            type: datetime
            column: TiempoEnArchivo
        observacion:
            type: string
            length: '1000'
            nullable: true
            column: Observacion
            
    manyToOne:
        fichaDeProceso:
            targetEntity: FichaDeProceso
            joinColumn: 
                name: fichaDeProceso_id
                referencedColumnName: id
        personaResponsable:
            targetEntity: Persona
            joinColumn: 
                name: persona_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
