INFT\prosgaBundle\Entity\Sector:
    type: entity
    table: Sector
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '200'
            column: Nombre
        ubicacion:
            type: string
            length: 255
            column: Ubicacion
        metros2:
            type: float
            column: Metros2
            nullable: true
        observacion:
            type: string
            length: 255
            nullable: true
            column: Observacion
    
    lifecycleCallbacks: {  }
