INFT\prosgaBundle\Entity\TiposIncidencias:
    type: entity
    table: TiposIncidencias
    repositoryClass: TiposIncidenciasRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
            column: Nombre
        valorPermitido:
            type: float
            column: ValorPermitido
            nullable: true
        descripcion:
            type: string
            length: '500'
            nullable: true
            column: Descripcion
        observacion:
            type: string
            length: '1000'
            nullable: true
            column: Observacion
        fechaCreacion:
            type: datetime
            column: FechaCreacion            

    manyToOne:
        frecuencia:
            targetEntity: Frecuencia
            joinColumn:
                name: frecuencia_id
                referencedColumnName: id
        fichaDeProceso:
            targetEntity: FichaDeProceso
            joinColumn:
                name: fichaDeProceso_id
                referencedColumnName: id
        personaResponsable:
            targetEntity: Persona
            joinColumn:
                name: personaResponsable_id
                referencedColumnName: id
                
    lifecycleCallbacks: {  }
