prosga_auditoria:
    resource: "routing/auditoria.yml"
    prefix: /auditoria
    
prosga_actividades:
    resource: "routing/actividades.yml"        
    prefix: /actividades
    
prosga_fichadeproceso:
    resource: "routing/fichadeproceso.yml"        
    prefix: /fichadeproceso
    
prosga_fichadeproceso_entrada:
    resource: "routing/fichadeprocesoentrada.yml"        
    prefix: /fichadeprocesoentrada
    
prosga_fichadeproceso_historial:
    resource: "routing/fichadeprocesohistorial.yml"        
    prefix: /fichadeprocesohistorial
    
prosga_fichadeproceso_salida:
    resource: "routing/fichadeprocesosalida.yml"        
    prefix: /fichadeprocesosalida    

prosga_homepage:
    path:     /
    defaults: { _controller: prosgaBundle:Default:home }

## OTROS

prosga_consultas:
    path:     /consultas
    defaults: { _controller: prosgaBundle:Default:consultas }
    
prosga_acercade:
    path:     /acercade
    defaults: { _controller: prosgaBundle:Default:acercade }    