prosga_auditoria:
    resource: "routing/auditoria.yml"
    prefix: /auditoria
    
prosga_actividades:
    resource: "routing/actividades.yml"        
    prefix: /actividades

prosga_homepage:
    path:     /
    defaults: { _controller: prosgaBundle:Default:home }

## OTROS

prosga_consultas:
    path:     /consultas
    defaults: { _controller: prosgaBundle:Default:consultas }
    
prosga_acercade:
    path:     /acercade
    defaults: { _controller: prosgaBundle:Default:acercade }    